# Generated by Django 6.0.5 on 2026-05-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failureanalysis',
            name='predicted_attack_type',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Predicted Attack Type'),
        ),
        migrations.AlterField(
            model_name='failureanalysis',
            name='true_attack_type',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='True Attack Type'),
        ),
    ]
