# Generated by Django 6.0.5 on 2026-05-23 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_api', '0002_alter_failureanalysis_predicted_attack_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failureanalysis',
            name='ActionAttack_level',
            field=models.FloatField(blank=True, null=True, verbose_name='Action Attack Level'),
        ),
        migrations.AlterField(
            model_name='failureanalysis',
            name='ConstellationConfig',
            field=models.FloatField(blank=True, null=True, verbose_name='Constellation Config'),
        ),
        migrations.AlterField(
            model_name='failureanalysis',
            name='ExperiencePoolAttack_level',
            field=models.FloatField(blank=True, null=True, verbose_name='Experience Pool Attack Level'),
        ),
        migrations.AlterField(
            model_name='failureanalysis',
            name='ModelTampAttack_level',
            field=models.FloatField(blank=True, null=True, verbose_name='Model Tamp Attack Level'),
        ),
        migrations.AlterField(
            model_name='failureanalysis',
            name='RewardAttack_level',
            field=models.FloatField(blank=True, null=True, verbose_name='Reward Attack Level'),
        ),
        migrations.AlterField(
            model_name='failureanalysis',
            name='StateObservationAttack_level',
            field=models.FloatField(blank=True, null=True, verbose_name='State Observation Attack Level'),
        ),
        migrations.AlterField(
            model_name='failureanalysis',
            name='StateTransferAttack_level',
            field=models.FloatField(blank=True, null=True, verbose_name='State Transfer Attack Level'),
        ),
    ]
