# Generated by Django 6.0.5 on 2026-05-23 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_api', '0003_alter_failureanalysis_actionattack_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfhealing',
            name='node_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Node ID'),
        ),
    ]
