# Generated by Django 6.0.5 on 2026-05-25 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_api', '0004_alter_selfhealing_node_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(default='running', max_length=20)),
                ('current_stage', models.CharField(default='Simulation', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
