# Generated by Django 6.0.5 on 2026-05-25 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_api', '0005_pipelinetask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stepevaluate',
            name='ActionAttack_level',
        ),
        migrations.RemoveField(
            model_name='stepevaluate',
            name='ConstellationConfig',
        ),
        migrations.RemoveField(
            model_name='stepevaluate',
            name='DegradedEdgeRatio',
        ),
        migrations.RemoveField(
            model_name='stepevaluate',
            name='EdgeBandwidthDecreaseStd',
        ),
        migrations.RemoveField(
            model_name='stepevaluate',
            name='EdgeBandwidthMeanDecreaseRatio',
        ),
        migrations.RemoveField(
            model_name='stepevaluate',
            name='EdgeDisconnectRatio',
        ),
        migrations.RemoveField(
            model_name='stepevaluate',
            name='ExperiencePoolAttack_level',
        ),
        migrations.RemoveField(
            model_name='stepevaluate',
            name='MeanIntervalTime',
        ),
        migrations.RemoveField(
            model_name='stepevaluate',
            name='ModelTampAttack_level',
        ),
        migrations.RemoveField(
            model_name='stepevaluate',
            name='PacketGenerationInterval',
        ),
        migrations.RemoveField(
            model_name='stepevaluate',
            name='PacketSizeMean',
        ),
        migrations.RemoveField(
            model_name='stepevaluate',
            name='PacketSizeStd',
        ),
        migrations.RemoveField(
            model_name='stepevaluate',
            name='PoissonRate',
        ),
        migrations.RemoveField(
            model_name='stepevaluate',
            name='RewardAttack_level',
        ),
        migrations.RemoveField(
            model_name='stepevaluate',
            name='StateObservationAttack_level',
        ),
        migrations.RemoveField(
            model_name='stepevaluate',
            name='StateTransferAttack_level',
        ),
        migrations.CreateModel(
            name='TestScenarioConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_timestamp', models.CharField(max_length=64, verbose_name='Start Timestamp')),
                ('test_id', models.IntegerField(verbose_name='Test ID')),
                ('ConstellationConfig', models.IntegerField(verbose_name='Constellation Config')),
                ('DegradedEdgeRatio', models.FloatField(verbose_name='Degraded Edge Ratio')),
                ('EdgeDisconnectRatio', models.FloatField(verbose_name='Edge Disconnect Ratio')),
                ('EdgeBandwidthMeanDecreaseRatio', models.FloatField(verbose_name='Edge Bandwidth Mean Decrease Ratio')),
                ('EdgeBandwidthDecreaseStd', models.FloatField(verbose_name='Edge Bandwidth Decrease Std')),
                ('PoissonRate', models.FloatField(verbose_name='Poisson Rate')),
                ('MeanIntervalTime', models.FloatField(verbose_name='Mean Interval Time')),
                ('PacketGenerationInterval', models.FloatField(verbose_name='Packet Generation Interval')),
                ('PacketSizeMean', models.FloatField(verbose_name='Packet Size Mean')),
                ('PacketSizeStd', models.FloatField(verbose_name='Packet Size Std')),
                ('StateObservationAttack_level', models.IntegerField(verbose_name='State Observation Attack Level')),
                ('ActionAttack_level', models.IntegerField(verbose_name='Action Attack Level')),
                ('StateTransferAttack_level', models.IntegerField(verbose_name='State Transfer Attack Level')),
                ('RewardAttack_level', models.IntegerField(verbose_name='Reward Attack Level')),
                ('ExperiencePoolAttack_level', models.IntegerField(verbose_name='Experience Pool Attack Level')),
                ('ModelTampAttack_level', models.IntegerField(verbose_name='Model Tamp Attack Level')),
            ],
            options={
                'verbose_name': 'Test Scenario Config',
                'db_table': 'test_scenario_config',
                'unique_together': {('start_timestamp', 'test_id')},
            },
        ),
        migrations.AddField(
            model_name='stepevaluate',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_evaluations', to='security_api.testscenarioconfig'),
        ),
    ]
