# Generated by Django 6.0.5 on 2026-05-26 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_api', '0006_remove_stepevaluate_actionattack_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testscenarioconfig',
            name='scenario_similarity',
            field=models.FloatField(blank=True, null=True, verbose_name='Scenario Similarity'),
        ),
    ]
