# Generated by Django 6.0.5 on 2026-05-27 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_api', '0007_testscenarioconfig_scenario_similarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='testscenarioconfig',
            name='latest_coverage',
            field=models.FloatField(blank=True, null=True, verbose_name='Latest Coverage'),
        ),
    ]
