# Generated by Django 6.0.5 on 2026-05-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_api', '0008_testscenarioconfig_latest_coverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='testscenarioconfig',
            name='failure_detection_accuracy',
            field=models.FloatField(blank=True, null=True, verbose_name='Failure Detection Accuracy'),
        ),
    ]
